--配置表信息 
local Conf = {
	["mx_nn_type"] = {'无牛','牛一','牛二','牛三','牛四','牛五','牛六','牛七','牛八','牛九','牛牛','银牛','金牛'},
	-- mx_tip -->
	["mx_updealer_fail_nomoney"]='钱数不足{0},无法上庄',
	["mx_wait_next_start"]='等待下一局开始..',
	["mx_wait_bankup"]='等待玩家上庄..',
	["mx_wait_ready"]='等待玩家就绪..',
	["mx_game_waiting"]='游戏等待中..',
	["mx_err_game_beting"]='下注阶段无法申请上庄',
	["mx_err_game_xiazhuang"]='下注阶段无法申请下庄',
	-- game_bet_err_code -->
	["mx_bet_err_0"]='已到庄家上限',
	["mx_bet_err_1"]='已到玩家上限',
	["mx_bet_err_2"]='带入钱币不足',
	["mx_bet_err_3"]='到达盘面上限',
	["mx_bet_err_4"]='坐下失败',
	["mx_bet_err_5"]='已经坐下',
	["mx_bet_err_6"]='座位被占了',
	["mx_bet_err_7"]='没有空座了',
	["mx_bet_err_8"]='你尚未入座，无法发送表情',
	["mx_bet_err_9"]='请先离开座位',
	["mx_bet_err_10"]='购买失败',
	["mx_bet_err_11"]='用户携带金币不足，无法购买',
	["mx_bet_err_12"]='当前只有一桌，无法换桌',
	-- game_str -->
	["mx_label_0"]='昵称:',
	["mx_label_1"]='战绩:',
	["mx_label_2"]='局数:',
	["mx_label_3"]='昵称:',
	["mx_label_4"]='战绩:',
	["mx_label_5"]='游戏币:',
	["mx_bakup_label"]='{0} 上庄',
	-- unit -->
	["mx_bet_unit"]='万',
	["mx_settle_unit_1"]='倍',
	["mx_settle_fmat_0"]='{0} x{1}倍\n+{2}',
	["mx_settle_fmat_1"]='{0} x{1}倍\n{2}',
	["mx_settle_fmat_2"]='{0}\n无成绩',
	["mx_settle_fmat_3"]='{0}\n+{1}',
	["mx_settle_fmat_4"]='{0}\n{0}',
	["mx_settle_fmat_5"]='{0}\n无成绩',
	["ssd"]='',
	["message_prompt_0"]='莫偷鸡，偷鸡必被抓！',
	["message_prompt_1"]='别挣扎了，大奖非我莫属！',
	["message_prompt_2"]='我的宝剑已经饥渴难耐了！',
	["message_prompt_3"]='冷静！冲动是魔鬼！',
	["message_prompt_4"]='对子在手，天下无敌！',
	["message_prompt_5"]='这手牌打的不错，赢的漂亮！',
	["message_prompt_6"]='快点下注吧！爷时间宝贵！',
	["message_prompt_7"]='很高兴能和大家一起打牌.',
	["message_prompt_8"]='赢钱了别走，留下你的姓名！',
	["message_prompt_9"]='难道你看穿我的底牌了吗？',
	["message_prompt_10"]='各位爷，让看看翻牌再加注吧！',
	["message_prompt_11"]='输惨了啦!',
	["message_prompt_12"]='似乎有埋伏，不可轻举妄动.',
	["message_prompt_13"]='你牌技这么好，地球人知道吗？',
	["message_prompt_14"]='想什么呢？快点！',
	["message_error_1"]='还未开始游戏，无法互送道具',
	["message_error_2"]='还未开始游戏，无法赠送礼品',
	["message_error_3"]='还未开始游戏，无法发送表情',
	["message_error_4"]='还未开始游戏，无法发送语音',
	["message_error_5"]='操作过于频繁，请稍后发送',
	["message_error_6"]='请选择语音之后再进行发送',
	
	["mahjonglanguage_0"]='快点啦！时间很宝贵的！',
	["mahjonglanguage_1"]='一路屁胡，走向胜利！',
	["mahjonglanguage_2"]='上碰下自摸，大家要小心喽！',
	["mahjonglanguage_3"]='好汉不胡头三把',
	["mahjonglanguage_4"]='先胡不算胡，后胡满金桌',
	["mahjonglanguage_5"]='呀！打错了怎么办？',
	["mahjonglanguage_6"]='卡！卡！卡！卡的人火大啊！',
	["mahjonglanguage_7"]='很高兴能和大家一起打牌',
	
	
	["hpsk_man_language_0"]='拜托，打快一点好吧',
	["hpsk_man_language_1"]='嘿嘿~看哥玩儿的就是寂寞',
	["hpsk_man_language_2"]='快点儿快点儿，哥还要去约会呢',
	["hpsk_man_language_3"]='等你这样打太阳都快落山了',
	["hpsk_man_language_4"]='哦~你干脆回去睡一觉再来吧',
	["hpsk_man_language_5"]='哇~这么好的牌',
	["hpsk_man_language_6"]='休息一下，开始咯',
	["hpsk_man_language_7"]='怎么这么慢，这打牌还是打太极呢',
	["hpsk_man_language_8"]='这样也行，I服了YOU',
	
	["hpsk_woman_language_0"]='拜托，打快一点好吗',
	["hpsk_woman_language_1"]='大哥~请你快一点啦',
	["hpsk_woman_language_2"]='诶诶诶，你打牌真龟诶',
	["hpsk_woman_language_3"]='嗯嗯嗯嗯，你们都欺负我',
	["hpsk_woman_language_4"]='嘿嘿嘿~看姐玩的就是心跳',
	["hpsk_woman_language_5"]='快点快点，姐还等着约会呢',
	["hpsk_woman_language_6"]='老娘跟你们拼啦',
	["hpsk_woman_language_7"]='你等和么呢，你等月亮姐姐呢',
	["hpsk_woman_language_8"]='哇哦，这么好的牌',
	
	["msg_ddz_0"]='大家好,给各位请安啦!',
	["msg_ddz_1"]='这牌你也敢叫地主，简直自寻死路.',
	["msg_ddz_2"]='喂！你倒是快点啊.',
	["msg_ddz_3"]='拖时间是没用滴!',
	["msg_ddz_4"]='出啊！好牌都留着下蛋呢?',
	["msg_ddz_5"]='不怕神一样的对手，就怕猪一样的队友',
	["msg_ddz_6"]='你很罗嗦诶！安静打牌好不!',
	["msg_ddz_7"]='别崇拜#,#只是个传说.',
	["msg_ddz_8"]='和你合作真是太愉快啦!',
	["msg_ddz_9"]='不好意思各位，我先走一步了.',
	["msg_ddz_10"]='这把牌实在太烂了!',
	["msg_ddz_11"]='牌好心情就好.',
}
return Conf